# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI (Gradle, Temurin, JDK 11)

on:
  pull_request:
    branches: main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows: [ 'Auto-format to Google Style Guide' ]
    types:
      - completed

jobs:
  buildGame:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: 'x64'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Desktop Jar generation
        run: ./gradlew :desktop:dist
  uploadJacocoReport:
      runs-on: ubuntu-latest
      needs: [buildGame]
      steps:
      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: jacoco
          path: tests/build/jacocoHtml
  uploadJar:
      runs-on: ubuntu-latest
      needs: [buildGame]
      steps:
      - name: Upload Desktop jar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: desktop.jar
          path: desktop/build/libs/desktop-1.0.jar
  uploadCheckstyle:
      runs-on: ubuntu-latest
      needs: [buildGame]
      steps:
      - name: Upload Core Checkstyle Report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: checkstyle-core
          path: core/build/reports/checkstyle/main.html
      - name: Upload Test Checkstyle Report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: checkstyle-test
          path: tests/build/reports/checkstyle/test.html
  discordAlert:
      runs-on: ubuntu-latest
      needs: [buildGame, uploadCheckstyle, uploadJacocoReport, uploadJar]
      steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: "${{ secrets.DISCORD_WEBHOOK }}"
        uses: Ilshidur/action-discord@master
        with:
          args: 'The branch is ready to be reviewed and merged to main.'
  release:
    runs-on: ubuntu-latest
    needs: [buildGame]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: desktop/build/libs/desktop-1.0.jar
          asset_name: Desktop JAR
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
      - name: Release
        uses: softprops/action-gh-release@v1


      



