name: Deploy Weekly
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  release-weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: 'x64'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Desktop Jar generation
        run: ./gradlew :desktop:dist
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Get Release Name
        run: output=$(python3 "tools/releaseNoGen.py")
        id: name
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         branch: "${{ env.STABLE_NAME }}"
         sha: '${{ github.event.pull_request.head.sha }}'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: "Stable"
           prerelease: true
           title: "Development Build"
           files: |
             desktop/build/libs/desktop-1.0.jar
  
  
  
  
  
